# Generated by Django 4.2.13 on 2026-05-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.CharField(max_length=10)),
                ('self_score', models.FloatField(default=0.0)),
                ('superior_score', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('grade_level_at_eval', models.CharField(max_length=10)),
                ('years_in_post', models.FloatField(default=0.0)),
                ('is_eligible_by_maturity', models.BooleanField(default=False)),
                ('is_csc_route', models.BooleanField(default=False)),
                ('requires_external_approval', models.BooleanField(default=False)),
                ('recommendation', models.CharField(choices=[('pending', 'Pending Review'), ('promote', 'Recommend for Promotion'), ('retain', 'Retain in Post'), ('defer', 'Defer Promotion')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('external_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('external_remarks', models.TextField(blank=True)),
                ('external_action_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-average_score'],
            },
        ),
    ]
