# Generated by Django 4.2.13 on 2026-05-19 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promotiondecision',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotiondecision',
            name='external_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotiondecision',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='promotiondecision',
            unique_together={('staff', 'cycle')},
        ),
    ]
