# Generated by Django 4.2.13 on 2026-05-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level_start', models.PositiveSmallIntegerField()),
                ('grade_level_end', models.PositiveSmallIntegerField()),
                ('required_years', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['grade_level_start'],
            },
        ),
    ]
