# Generated by Django 4.2.13 on 2026-05-19 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('REGISTER', 'Register'), ('PASSWORD_CHANGE', 'Password Change'), ('PAYMENT_STATUS_CHANGE', 'Payment Status Change'), ('PAYMENT_MANUAL_CONFIRM', 'Payment Manual Confirmation'), ('FORM_SUBMIT', 'Form Submission'), ('EVAL_SUBMIT', 'Evaluation Submission'), ('PROMOTION_CALC', 'Promotion Calculation'), ('PROMOTION_APPROVE', 'Promotion Approved'), ('ADMIN_OVERRIDE', 'Admin Override'), ('RULE_UPDATE', 'Promotion Rule Updated'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated')], max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['action', 'timestamp'], name='core_auditl_action_096de0_idx')],
            },
        ),
    ]
